# Generated by Django 5.2.16 on 2026-07-30 14:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('valor_padrao', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('triagem', models.JSONField(blank=True, default=dict)),
                ('descricao', models.TextField()),
                ('duracao_minuto', models.IntegerField(default=30)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
