# Generated by Django 5.2.16 on 2026-08-11 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedimentos', '0002_alter_procedimento_triagem'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='procedimento',
            table='procedimentos',
        ),
    ]
