# Generated by Django 5.2.16 on 2026-08-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimentos', '0003_alter_procedimento_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimento',
            name='triagem',
            field=models.TextField(default='Sem triagem'),
        ),
    ]
