# Generated by Django 5.2.16 on 2026-08-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedimentos', '0004_alter_procedimento_triagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimento',
            name='triagem',
            field=models.TextField(blank=True),
        ),
    ]
