# Generated by Django 5.2.16 on 2026-07-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('phone_number', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('complete_name', models.CharField(blank=True, max_length=150)),
                ('require_human', models.BooleanField(default=False)),
                ('complete_register', models.BooleanField(default=False)),
                ('origin_contact', models.TextField(default='whatsapp')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('convenio', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
