# Generated by Django 5.2.16 on 2026-08-11 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pacientes',
            options={'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='phone_number',
            field=models.CharField(max_length=13, primary_key=True, serialize=False, verbose_name='Número de Contato'),
        ),
        migrations.AlterModelTable(
            name='pacientes',
            table='pacientes',
        ),
    ]
