# Generated by Django 5.2.16 on 2026-08-13 01:28

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_alter_pacientes_options_alter_pacientes_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='created_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='updated_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
        ),
    ]
