# Generated by Django 5.2.16 on 2026-07-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procedimentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('numero', models.CharField(blank=True, max_length=13)),
                ('calendar_id', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('duracao', models.IntegerField(default=30)),
                ('dias_da_semana', models.JSONField(default=list)),
                ('horario_trabalho', models.JSONField(default=dict)),
                ('convenio', models.JSONField(blank=True, default=list)),
                ('restricao', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procedimentos', models.ManyToManyField(to='procedimentos.procedimento')),
            ],
        ),
    ]
