# Generated by Django 5.2.16 on 2026-08-11 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doutores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doutor',
            options={'verbose_name': 'Doutor', 'verbose_name_plural': 'Doutores'},
        ),
        migrations.AlterModelTable(
            name='doutor',
            table='doutores',
        ),
    ]
