# Generated by Django 5.2.16 on 2026-08-10 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.TextField(blank=True, null=True)),
                ('input_tokens', models.IntegerField()),
                ('output_tokens', models.IntegerField()),
                ('total_tokens', models.IntegerField()),
                ('model_name', models.CharField(blank=True, max_length=200, null=True)),
                ('provider', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usos_de_token', to='pacientes.pacientes')),
            ],
            options={
                'verbose_name': 'Uso de Token',
                'verbose_name_plural': 'Usos de Token',
                'db_table': 'token_usage',
            },
        ),
    ]
