# Generated by Django 5.2.16 on 2026-08-07 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doutores', '0001_initial'),
        ('pacientes', '0001_initial'),
        ('procedimentos', '0002_alter_procedimento_triagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('convenio_utilizado', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('canceled', 'Cancelado')], default='pending', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='doutores.doutor')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='pacientes.pacientes')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='procedimentos.procedimento')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['event_id'], name='agenda_agen_event_i_e6d762_idx'), models.Index(fields=['start_time'], name='agenda_agen_start_t_e99caf_idx')],
            },
        ),
    ]
