# Generated by Django 5.2.16 on 2026-08-11 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agendamento',
            new_name='agendamento_event_i_f03495_idx',
            old_name='agenda_agen_event_i_e6d762_idx',
        ),
        migrations.RenameIndex(
            model_name='agendamento',
            new_name='agendamento_start_t_a563a2_idx',
            old_name='agenda_agen_start_t_e99caf_idx',
        ),
        migrations.AlterModelTable(
            name='agendamento',
            table='agendamentos',
        ),
    ]
