# Generated by Django 5.2.16 on 2026-08-13 10:53

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_rename_agenda_agen_event_i_e6d762_idx_agendamento_event_i_f03495_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='created_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='updated_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
        ),
    ]
