# Generated by Django 5.2.16 on 2026-08-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('institucional', 'Institucional'), ('procedimentos', 'Procedimentos'), ('politicas', 'Políticas Internas')], max_length=100)),
                ('tipo_midia', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('txt', 'TXT')], max_length=50)),
                ('arquivo', models.FileField(upload_to='arquivos_rag/')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
