# Generated by Django 5.2.16 on 2026-08-05 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS vector;",
            reverse_sql="DROP EXTENSION IF EXISTS vector;",
        ),
    ]
