# Generated by Django 5.2.16 on 2026-08-05 01:04

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0002_enable_pgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('arquivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='arquivos.arquivo')),
            ],
        ),
    ]
