# Generated by Django 5.2.16 on 2026-08-11 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0003_embedding'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='arquivo',
            table='arquivos',
        ),
        migrations.AlterModelTable(
            name='embedding',
            table='embeddings',
        ),
    ]
