# Generated by Django 5.2.16 on 2026-08-05 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(blank=True, max_length=20, null=True)),
                ('agent_name', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='pacientes.pacientes')),
            ],
            options={
                'db_table': 'chat',
                'indexes': [models.Index(fields=['session_id'], name='chat_session_idx')],
            },
        ),
    ]
